server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  profiles:
   active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

app:
  urls:
    password-reset: ${APP_PASSWORD_RESET_URL}

security:
  rate-limit:
    forgot-password:
      capacity: 5
      refill-seconds: 10
    login:
      capacity: 5
      refill-seconds: 5
    refresh:
      capacity: 10
      refill-seconds: 1

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [requestId=%X{requestId}] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
  health:
    db:
      enabled: true
  info:
    env:
      enabled: true # Required for custom info properties

info:
  app:
    name: enterprise-order-suite
    description: Production-grade backend system
    version: 1.0.0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
