package com.enterprise.ordersuite.common.persistence;

import org.hibernate.annotations.IdGeneratorType;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * A ULID primary key generated by the application on insert (ADR-0009). Pair it with
 * {@code @JdbcTypeCode(SqlTypes.CHAR)} and {@code length = 26}: the column is {@code char(26)}.
 */
@IdGeneratorType(UlidIdGenerator.class)
@Retention(RUNTIME)
@Target(FIELD)
public @interface UlidId {
}
