CREATE TABLE IF NOT EXISTS roles (
    id BIGSERIAL PRIMARY KEY,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),

    name VARCHAR(50) NOT NULL UNIQUE
);
