-- Pre-launch baseline (ADR-0009, Build 1 Tenant foundation). Replaces V1-V21 once: ULID keys
-- (char(26) Crockford Base32, generated by the application), the restaurant as tenant
-- (ADR-0001), every timestamp an instant (D15). The legacy orders, products, roles and
-- user_profiles tables are gone (Q-90 a; Tenancy & Identity contract D-3, D-18).
-- Every local database is dropped and recreated after this change. From here on, never
-- edit an applied migration.

CREATE TABLE restaurants (
    id          CHAR(26)                 PRIMARY KEY,
    name        VARCHAR(80)              NOT NULL,
    slug        VARCHAR(40)              NOT NULL,
    timezone    VARCHAR(64)              NOT NULL,
    currency    VARCHAR(3)               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_restaurants_slug UNIQUE (slug),
    CONSTRAINT ck_restaurants_slug CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(slug) BETWEEN 3 AND 40),
    CONSTRAINT ck_restaurants_currency CHECK (currency IN ('BRL'))
);

CREATE TABLE users (
    id              CHAR(26)                 PRIMARY KEY,
    email           VARCHAR(254)             NOT NULL,
    first_name      VARCHAR(80)              NOT NULL,
    last_name       VARCHAR(80)              NOT NULL,
    phone           VARCHAR(20),
    -- Null until an invited user sets a password.
    password        VARCHAR(255),
    platform_admin  BOOLEAN                  NOT NULL DEFAULT FALSE,
    active          BOOLEAN                  NOT NULL DEFAULT TRUE,
    avatar_key      VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_users_email UNIQUE (email)
);

-- At most one membership per user (D-2); a platform admin has none.
CREATE TABLE memberships (
    id             CHAR(26)                 PRIMARY KEY,
    restaurant_id  CHAR(26)                 NOT NULL REFERENCES restaurants (id),
    user_id        CHAR(26)                 NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role           VARCHAR(16)              NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_memberships_user UNIQUE (user_id),
    CONSTRAINT ck_memberships_role CHECK (role IN ('OWNER', 'MANAGER', 'STAFF'))
);

CREATE INDEX ix_memberships_restaurant ON memberships (restaurant_id);

-- D16: a family is every token descended from one login; reuse revokes the family.
CREATE TABLE refresh_tokens (
    id          CHAR(26)                 PRIMARY KEY,
    user_id     CHAR(26)                 NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)              NOT NULL,
    family_id   UUID                     NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    revoked_at  TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX ix_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX ix_refresh_tokens_family ON refresh_tokens (family_id);

CREATE TABLE password_history (
    id             CHAR(26)                 PRIMARY KEY,
    user_id        CHAR(26)                 NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    password_hash  VARCHAR(255)             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_password_history_user_date ON password_history (user_id, created_at DESC);

-- Reset and invite tokens share this table (Tenancy & Identity schema notes): hash only,
-- one-time use.
CREATE TABLE password_reset_tokens (
    id          CHAR(26)                 PRIMARY KEY,
    user_id     CHAR(26)                 NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)              NOT NULL,
    purpose     VARCHAR(16)              NOT NULL DEFAULT 'RESET',
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_password_reset_tokens_purpose CHECK (purpose IN ('RESET', 'INVITE'))
);

CREATE INDEX ix_password_reset_tokens_user ON password_reset_tokens (user_id);
CREATE INDEX ix_password_reset_tokens_expires_at ON password_reset_tokens (expires_at);

-- restaurant_id is null only for platform-level events (restaurant created).
CREATE TABLE identity_audit_events (
    id              CHAR(26)                 PRIMARY KEY,
    restaurant_id   CHAR(26)                 REFERENCES restaurants (id),
    type            VARCHAR(64)              NOT NULL,
    actor_user_id   CHAR(26)                 REFERENCES users (id),
    target_user_id  CHAR(26)                 REFERENCES users (id),
    details         JSONB                    NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_identity_audit_events_type CHECK (type IN (
        'MEMBER_INVITED',
        'INVITE_RESENT',
        'ROLE_CHANGED',
        'MEMBER_DEACTIVATED',
        'MEMBER_REACTIVATED',
        'PASSWORD_CHANGED',
        'PASSWORD_RESET',
        'SIGNED_OUT_OTHER_DEVICES',
        'RESTAURANT_CREATED',
        'RESTAURANT_UPDATED'
    ))
);

CREATE INDEX ix_identity_audit_events_restaurant_created ON identity_audit_events (restaurant_id, created_at DESC);
CREATE INDEX ix_identity_audit_events_target_user ON identity_audit_events (target_user_id);
CREATE INDEX ix_identity_audit_events_actor_user ON identity_audit_events (actor_user_id);
